### ISSUE TITLE
Query fail post-auth

### ISSUE THREAD

**Issue by mlhickey** [microsoftgraph/console-csharp-connect-sample#17]
After successful auth, initial query with resulting token yields:

**Location header not present in redirection response**

Assuming this is buried down in the HTTP helper below the MSGraph SDK - any thoughts?

**Comment by jasonjoh** [comment]
Thanks for your interest in Microsoft Graph! We are archiving this sample, so I'm closing this issue. For a replacement C# console app sample, please see https://github.com/microsoftgraph/msgraph-training-dotnet-core. We apologize for any inconvenience.
