### ISSUE TITLE
Version Using .NET Core 2.0

### ISSUE THREAD

**Issue by mogulman52** [microsoftgraph/console-csharp-connect-sample#4]
Excellent getting started app.  Has anyone done a version of this using .Net Core 2.0?

**Comment by jasonjoh** [comment]
Thanks for your interest in Microsoft Graph! We are archiving this sample, so I'm closing this issue. For a replacement C# console app sample, please see https://github.com/microsoftgraph/msgraph-training-dotnet-core. We apologize for any inconvenience.
