### ISSUE TITLE
Microsoft account is experiencing technical problems

### ISSUE THREAD

**Issue by JosepBalague** [microsoftgraph/console-csharp-connect-sample#5]
Hi folks,

I'm getting this error after write my account ( myaccount@hotmail.com ). ClientID was  created previusly.

![imatge](https://user-images.githubusercontent.com/4932314/46247504-38ffc680-c404-11e8-962f-e340252cca1e.png)

I tried aftr and before updating neget packages

Cheers

**Comment by jasonjoh** [comment]
Thanks for your interest in Microsoft Graph! We are archiving this sample, so I'm closing this issue. For a replacement C# console app sample, please see https://github.com/microsoftgraph/msgraph-training-dotnet-core. We apologize for any inconvenience.
