### ISSUE TITLE
IE11 Script Error on Microsoft Graph oauth page

### ISSUE THREAD

**Issue by laikoni** [microsoftgraph/console-csharp-connect-sample#7]
When running the example, the login window shows a script error:
 `Object doesn't support this property or method "startsWith"` ([Screenshot](https://i.stack.imgur.com/OqFUf.png))

As far as I can tell, the login dialog opens an Internet Explorer instance and navigates to the URL specified in the error (https://login.microsoftonline.com/common/oauth2/v2.0/authorize) and indeed visiting this URL in IE produces the same error. ([Screenshot 2](https://i.stack.imgur.com/7Hc47.png))

Clicking on "OK" to abort the script results in a blank page.

This issue breaks my app as no login is possible. Two days ago on Monday 7th the same code worked as expected.

**Comment by jasonjoh** [comment]
Thanks for your interest in Microsoft Graph! We are archiving this sample, so I'm closing this issue. For a replacement C# console app sample, please see https://github.com/microsoftgraph/msgraph-training-dotnet-core. We apologize for any inconvenience.
