### ISSUE TITLE
Using an http proxy

### ISSUE THREAD

**Issue by jimmybourque** [microsoftgraph/console-csharp-connect-sample#9]
Hi,

I'm trying to use this source behind an http proxy. I get an HTTP 407 Access Denied.
Do you have a way to setting up this?

I don't find how to fix this.

Thanks in advance for you help!

Jimmy

**Comment by jasonjoh** [comment]
Thanks for your interest in Microsoft Graph! We are archiving this sample, so I'm closing this issue. For a replacement C# console app sample, please see https://github.com/microsoftgraph/msgraph-training-dotnet-core. We apologize for any inconvenience.
